// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserSaver is an autogenerated mocks type for the UserSaver type
type UserSaver struct {
	mock.Mock
}

// SaveUser provides a mocks function with given fields: ctx, username, passHash, email, firstName, lastName
func (_m *UserSaver) SaveUser(ctx context.Context, username string, passHash []byte, email string, firstName string, lastName string) (*uuid.UUID, error) {
	ret := _m.Called(ctx, username, passHash, email, firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 *uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string, string, string) (*uuid.UUID, error)); ok {
		return rf(ctx, username, passHash, email, firstName, lastName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string, string, string) *uuid.UUID); ok {
		r0 = rf(ctx, username, passHash, email, firstName, lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, string, string, string) error); ok {
		r1 = rf(ctx, username, passHash, email, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserSaver creates a new instance of UserSaver. It also registers a testing interface on the mocks and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSaver {
	mock := &UserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
